### ISSUE TITLE
Server stops working

### ISSUE THREAD

**Issue by Pengu1no** [thelastnoc/dayz-sa_linuxserver#15]
`$ bash dayzserver monitor`
```
[ DayZ ] Server not running.
[ DayZ ] Starting server...
```
Server lives for about 10 seconds and commits a suicide. Do you have any idea what's going wrong?

**Comment by Pengu1no** [comment]
`dayz@dayz:~/dayz-sa_linuxserver/script$ bash dayzserver start`
`[ DayZ ] Starting server...`
`dayz@dayz:~/dayz-sa_linuxserver/script$ bash dayzserver start`
`[ DayZ ] Server already running.`
`dayz@dayz:~/dayz-sa_linuxserver/script$ bash dayzserver start`
`[ DayZ ] Server already running.`
`dayz@dayz:~/dayz-sa_linuxserver/script$ bash dayzserver start`
`[ DayZ ] Server already running.`
`dayz@dayz:~/dayz-sa_linuxserver/script$ bash dayzserver start`
`[ DayZ ] Server already running.`
`dayz@dayz:~/dayz-sa_linuxserver/script$ bash dayzserver start`
`[ DayZ ] Starting server...`
![image](https://user-images.githubusercontent.com/26686814/58293758-8552a900-7dcf-11e9-8fab-e66ab99689ee.png)
And it does not listen 2302 port

**Comment by thelastnoc** [comment]
The server is not working anymore since Beta! Not the fault of the script.
Ask the DayZ Developer for Linux support.
