### ISSUE TITLE
NOT WORKING with DayZ Standalone v1.x!

### ISSUE THREAD

**Issue by thelastnoc** [thelastnoc/dayz-sa_linuxserver#18]
NOT WORKING with DayZ Standalone v1.x!

**Comment by RiDDiX** [comment]
Any fix coming for DayZ SA v1.x?

**Comment by DjBomberpilot** [comment]
is the script updated again?

**Comment by thelastnoc** [comment]
Updated to work with 1.14 Experimental Server.
