### ISSUE TITLE
Script not downloading and or update mods

### ISSUE THREAD

**Issue by Fmslick** [thelastnoc/dayz-sa_linuxserver#22]
Just installed and added the mods ID one pre-line and said in workshop.cfg , start the server and nothing... am I missing some?

Note have not added to dayzserver.cfg -mod=@xxx; yet, waiting to see what the naming scheme was going to look like!

**Comment by thelastnoc** [comment]
After adding the Workshop IDs into the `workshop.cfg`, mods are only downloaded while installing/updating the server or running the `./dayzserver ws` command.
Also there seem to be an issue if the steamlogin is set to `anonymous`.

To start the server with mods, you have to enter the mod names into the script config `.dayzserver.cfg`
Mods with spaces in their names should work now.

**Comment by thelastnoc** [comment]
Now it will download mods right after you add them to the config.

**Comment by Fmslick** [comment]
> After adding the Workshop IDs into the `workshop.cfg`, mods are only downloaded while installing/updating the server or running the `./dayzserver ws` command. Also there seem to be an issue if the steamlogin is set to `anonymous`.

Nice `/dayzserver ws` worked to download the mods, I see you are using steamCMD running Verifying to get the mods?
I removed the `anonymous` part.

> To start the server with mods, you have to enter the mod names into the script config `.dayzserver.cfg` Mods with spaces in their names should work now.

It does

> Now it will download mods right after you add them to the config.

That it does.

///
A thing to maybe add before mods start to download is to ask where are `your` mods located, if I recall they can be in './serverfiles/mods/*,*'  or something like that so they can live and load in there own folder! 

&& maybe add some where that you have to move the `key` files in to `/serverfiles/keys/` folder... There will be someone asking about that and why the server is not working. JS :p

**Comment by Fmslick** [comment]
Do I still need the `${workshop}` in the server startup command line?

`# modify carefully! server won't start if syntax is corrupt!
dayzparameter=" -config=${config} -port=${port} -freezecheck ${BEpath} ${profiles} ${logs} ${workshop}"`

**Comment by thelastnoc** [comment]
Mods are downloaded to "serverfiles/steamapps/workshop/content/221100". You can only tell where steamapps will be created.
From there the script will link the mods with their @Name. That way it's not necessary to copy the mods somewhere else if they get updated.

Whoever want to use mods should read the instructions from the modpage. It's the same like on windows.^^
