### ISSUE TITLE
Centos 8 | Installation of DayZ Linux [NOT EXPERIMENTAL VERSION]

### ISSUE THREAD

**Issue by ItsVinnyX** [thelastnoc/dayz-sa_linuxserver#25]
Error:
![image](https://user-images.githubusercontent.com/5962854/144780906-bf4561c1-12da-45f2-9048-3eb6752e11aa.png)

Directory:
![image](https://user-images.githubusercontent.com/5962854/144780920-207b0395-93a4-4ad4-9dff-8b319c8970eb.png)

How would you go about installing this on Centos 7?

**Comment by Fmslick** [comment]
I do believe this is not been tested for CentOS 7 and it's not supposed at this time. Debian, Ubuntu and pop_os looks to be supposed. I could be wrong.

I have got it runs on Ubuntu 20.04 with no issues other than my own rushing and not reading lol. There is a good how to on steam by thelastnoc that has a bit more information, I think they just have not gotten around to updating git yet.

**Comment by ItsVinnyX** [comment]
I am trying to do it with Wine but I can't figure it out!

**Comment by Fmslick** [comment]
The script is for DayZ Standalone 1.15 Exprimental that is the only version that is Linux supported at this time. You don't need Wine or anything that simulates running .exe .. I would suggest you use Ubuntu or Debian.

**Comment by ItsVinnyX** [comment]
> The script is for DayZ Standalone 1.15 Exprimental that is the only version that is Linux supported at this time. You don't need Wine or anything that simulates running .exe .. I would suggest you use Ubuntu or Debian.

Yeah, I would like to run not experimental we are struggling to get it going on CentOS 8. We are quite lost. There's nothing on it.

**Comment by Fmslick** [comment]
> > The script is for DayZ Standalone 1.15 Exprimental that is the only version that is Linux supported at this time. You don't need Wine or anything that simulates running .exe .. I would suggest you use Ubuntu or Debian.
> 
> Yeah, I would like to run not experimental we are struggling to get it going on CentOS 8. We are quite lost. There's nothing on it.

CentOS 7 or 8 ?

....
https://steamcommunity.com/sharedfiles/filedetails/?id=1517338673
Looks to be more up-to-date than here on git.

**Comment by ItsVinnyX** [comment]
> > > The script is for DayZ Standalone 1.15 Exprimental that is the only version that is Linux supported at this time. You don't need Wine or anything that simulates running .exe .. I would suggest you use Ubuntu or Debian.
> > 
> > 
> > Yeah, I would like to run not experimental we are struggling to get it going on CentOS 8. We are quite lost. There's nothing on it.
> 
> CentOS 7 or 8 ?
> 
> .... https://steamcommunity.com/sharedfiles/filedetails/?id=1517338673 Looks to be more up-to-date than here on git.

We use Centos 8 I accidentally said 7.

**Comment by ItsVinnyX** [comment]
But we do not want to use Experimental we want to create a 1.15.154337 modded server.

**Comment by ItsVinnyX** [comment]
So we tried installing wine, we remote into our dedicated machine via PuTTy.

Do you have Discord by any chance?

My buddy might check out the ticket too, so just let us know thanks!

**Comment by Fmslick** [comment]
That would be up to thelastnoc at this point.

**Comment by ItsVinnyX** [comment]
> That would be up to thelastnoc at this point.

Truly a shame.

**Comment by Fmslick** [comment]
So I did some digging and testing. The only version of DayZ that is supported by Linux at this time is the experimental version via the devs of DayZ. This script only works with that version as I did try to pull down the stable version but it was the stable version of experimental as it would seem. So at this time I would say it's out of the quest right now seeing to as this script is designed to run only the Linux supported version of DayZ. 

Edit, there is not a stable version of DayZ currently supported by Linux.

Note, I am not the dev I'm just someone trying to help.

**Comment by ItsVinnyX** [comment]
Thanks man

**Comment by thelastnoc** [comment]
Hello there. I wasn't aware that you have issues with the dayz server setup. 
Unfortunately i don't have the time to test the script with all the Linux distributions.

To clarfiy. 
The script in the master branch is only for the current experimental branch on steam.
The Devs are still testing the dayz server files for linux. We only can report any bugs to the devs so they can release it to stable.

The last version that worked with wine was 0.63. (script is still here on github in the windows-wine branch)
I did some tests with later versions but they didn't work anymore because of memory crashes.

--------------------

You can look at the setup for the arma 3 server for linux at  (Linux Game Server Managers)

https://linuxgsm.com/servers/arma3server/

And  try to adapt it to dayz.

---------------------
### **The old script that worked with wine is not supported anymore mainly because the server crashes and they didn't fix it.**

**Comment by thelastnoc** [comment]
Just did a test on a fresh installed CentOS 8. Works like on Debian.
https://steamcommunity.com/sharedfiles/filedetails/?id=1517338673
