### ISSUE TITLE
confuging versionsnumber

### ISSUE THREAD

**Issue by Tealk** [thelastnoc/dayz-sa_linuxserver#31]
The version number 1.15 is confusing

https://github.com/thelastnoc/dayz-sa_linuxserver/blob/d005a1e0d8068f05d22f372d20a951a6955642ee/script/dayzserver#L435

perhaps the variable would be more suitable?
${currentbuild}

**Comment by vaesanti** [comment]
work only in 1.5 EXPERIMENTAL ??

**Comment by Tealk** [comment]
theoretically you can switch to the stable build and then it would be the 1.6
yes it doesn't work on linux but it would still be nicer if it wasn't a hardcoded version

**Comment by vaesanti** [comment]
> theoretically you can switch to the stable build and then it would be the 1.6 yes it doesn't work on linux but it would still be nicer if it wasn't a hardcoded version

how to change for stable version?

**Comment by Tealk** [comment]
this has no effect because the stable version does not provide linux files

**Comment by thelastnoc** [comment]
What confuses me is that you are confused about something so trivial.

The variable `${currentbuild}` for the current version is `8464361`. Just saying

Whenever you want to follow the updates take a look at https://steamdb.info/app/1042420/
