### ISSUE TITLE
Server restarting?

### ISSUE THREAD

**Issue by Kudris** [thelastnoc/dayz-sa_linuxserver#9]
How to set server restart every 6 hours? 
Thanks...

**Comment by thelastnoc** [comment]
Logged in as the user dayz run:
> crontab -e

 and add 

> 0 */6 * * * /home/dayz/dayzserver restart > /dev/null 2>&1

If you want specific times
> 0 0,6,12,18 * * * /home/dayz/dayzserver restart > /dev/null 2>&1

For more infos about cronjobs: https://en.wikipedia.org/wiki/Cron

**Comment by Kudris** [comment]
I set 0 */6 * * * /home/dayz/dayzserver restart > /dev/null 2>&1 in crontab -e
http://prntscr.com/lacjr0
After 10 hours server no restarted... why? :O

**Comment by thelastnoc** [comment]
You are in the system-wide crontab file. 
In that file you have to set the username.

> 0 */6 * * * dayz /home/dayz/dayzserver restart > /dev/null 2>&1
